os: Visual Studio 2015

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  MINICONDA: "C:\\Miniconda36-x64"

configuration: Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: git submodule update --init --recursive
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=3.6 cython numpy pytest
  - activate test-env
  - pip install .
  - python setup.py install
  - python -m spacy download en

build: off

test_script:
  - pytest --durations=0 -v tests
